django_marketplace/core/urls.py
"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views_dir. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views_dir
    1. Add an import:  from my_app import views_dir
    2. Add a URL to urlpatterns:  path('', views_dir.home, name='home')
Class-based views_dir
    1. Add an import:  from other_app.views_dir import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from products.views import HomeView


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='admin'),
    path('product/', include('products.urls')),
    path('order/', include('orders.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('carts.urls')),
    path('', HomeView.as_view(), name='home'),
    path('comparison/', include('comparisons.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

django_marketplace/orders/urls.py
from django.urls import path
from .views_dir import OrderProcessView, OrderPaymentView, ProgressPaymentView, OrderDetailView

app_name = "orders"

urlpatterns = [
    path('order=<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('proceed/', OrderProcessView.as_view(), name='order_proceed'),
    path('proceed/<int:pk>/payment', OrderPaymentView.as_view(), name='order_payment'),
    path('proceed/<int:pk>/payment_progress', ProgressPaymentView.as_view(), name='payment_progress'),
]

django_marketplace/products/urls.py
from django.urls import path, include
from django.conf import settings
from .views import *
from .views_dir import SaleView

app_name = "products"

urlpatterns = [
    path('discounts/', DiscountListView.as_view(), name='discounts_list'),
    path('catalog/', ProductsListView.as_view(), name="products_list"),
    path('catalog/sale/', SaleView.as_view(), name='sale_list'),
    path('<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    path('add-review/<slug:slug>/', ReviewCreateView.as_view(), name='review_create'),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include("debug_toolbar.urls")),
                  ] + urlpatterns

django_marketplace/orders/models.py
from django.db import models
from django.conf import settings
from products.models import SellerPrice


class Order(models.Model):
    """
    Модель заказа пользователя.
    Атрибуты:
        user (ForeignKey): Пользователь, который сделал заказ.
        products (ManyToManyField): Товары, включенные в заказ.
        total_price (DecimalField): Общая стоимость заказа.
        status (CharField): Статус заказа.
        created_at (DateTimeField): Дата создания заказа.
        updated_at (DateTimeField): Дата последнего обновления заказа.
    """
    STATUS_CHOICES = [
        ('pending', 'Ожидает обработки'),
        ('processed', 'Обрабатывается'),
        ('shipped', 'Отправлен'),
        ('delivered', 'Доставлен'),
        ('canceled', 'Отменен')
    ]

    DELIVERY_OPTIONS = [
        ('ordinary', 'Обычная доставка'),
        ('express', 'Экспресс доставка'),
    ]

    PAYMENT_OPTIONS = [
        ('online', 'Онлайн картой'),
        ('someone', 'Онлайн со случайного чужого счета'),
    ]

    PAYMENT_STATUS = [
        ('unpaid', 'Не оплачен'),
        ('paid', 'Оплачен'),
        ('error', 'Ошибка оплаты')
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Пользователь'
    )
    total_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Общая стоимость'
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='pending',
        verbose_name='Статус'
    )
    city = models.CharField(
        blank=True,
        max_length=50,
        verbose_name='Город'
    )
    address = models.CharField(
        blank=True,
        max_length=100,
        verbose_name='Адрес'
    )
    delivery_option = models.CharField(
        default=DELIVERY_OPTIONS[0],
        max_length=20,
        choices=DELIVERY_OPTIONS,
    )
    payment_option = models.CharField(
        default=PAYMENT_OPTIONS[0],
        max_length=20,
        choices=PAYMENT_OPTIONS
    )
    payment_status = models.CharField(
        default='unpaid',
        max_length=20,
        choices=PAYMENT_STATUS
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    def __str__(self):
        return f"Заказ #{self.id} от {self.user.email}"

    def get_delivery_label(self):
        return dict(self.DELIVERY_OPTIONS).get(self.delivery_option, self.delivery_option)

    def get_payment_label(self):
        return dict(self.PAYMENT_OPTIONS).get(self.payment_option, self.payment_option)

    def get_payment_status_label(self):
        return dict(self.PAYMENT_STATUS).get(self.payment_status, self.payment_status)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-created_at']


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='order_items',
        verbose_name='Заказ'
    )
    seller_price = models.ForeignKey(
        SellerPrice,
        on_delete=models.CASCADE,
        related_name='seller_price',
        verbose_name='Цена'
    )
    quantity = models.PositiveIntegerField(verbose_name="Количество")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

django_marketplace/templates/templates_order/order_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %} {% translate "Заказ" %} {% endblock %}

{% load carts_tags %}
{% load order_tags %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{% translate "Заказ" %} №{{ order.id }}</h1>
            </div>
        </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <div class="Section-content">
                <div class="Orders"></div>
                <div class="Order">
                    <div class="Order-infoBlock">
                        <div class="Order-personal">
                            <div class="row">
                                <div class="row-block">
                                    <div class="Order-info Order-info_date">
                                        <div class="Order-infoType">{% translate "Дата заказа"%}:</div>
                                        <div class="Order-infoContent">{{ order.created_at|date:"d.m.Y" }}</div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">{% translate "ФИО" %}:</div>
                                        <div class="Order-infoContent">{{ order.user.first_name }} {{ order.user.last_name }}</div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">{% translate "Телефон" %}:</div>
                                        <div class="Order-infoContent">{{ order.user.profile.phone }}</div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">{% translate "E-mail" %}:</div>
                                        <div class="Order-infoContent">{{ order.user.email }}</div>
                                    </div>
                                </div>
                                <div class="row-block">
                                    <div class="Order-info Order-info_delivery">
                                        <div class="Order-infoType">{% translate "Тип доставки" %}:</div>
                                        <div class="Order-infoContent">{% translate order.get_delivery_option_display %}</div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">{% translate "Город" %}:</div>
                                        <div class="Order-infoContent">{{ order.city }}</div>
                                    </div>
                                    <div class="Order-info">
                                        <div class="Order-infoType">{% translate "Адрес" %}:</div>
                                        <div class="Order-infoContent">{{ order.address }}</div>
                                    </div>
                                    <div class="Order-info Order-info_pay">
                                        <div class="Order-infoType">{% translate "Оплата" %}:</div>
                                        <div class="Order-infoContent">{% translate order.get_payment_option_display %}</div>
                                    </div>
                                    <div class="Order-info Order-info_status">
                                        <div class="Order-infoType">{% translate "Статус" %}:</div>
                                        <div class="Order-infoContent">{% translate order.get_status_display %}</div>
                                    </div>
                                    {% if order.payment_status == 'unpaid' %}
                                    <div class="Order-info Order-info_error">
                                        <div class="Order-infoType">{% translate "Оплата не прошла" %}:</div>
                                        <div class="Order-infoContent">{% translate "Оплата не выполнена" %}</div>
                                    </div>
                                    {% elif order.payment_status == 'error' %}
                                    <div class="Order-info Order-info_error">
                                        <div class="Order-infoType">{% translate "Ошибка" %}:</div>
                                        <div class="Order-infoContent">{% translate "Произошла ошибка при оплате. Попробуйте снова или выберите другой способ оплаты." %}
                                        </div>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="Cart Cart_order">
                            {% for i_item in order.order_items.all %}
                            <div class="Cart-product">
                                <div class="Cart-block Cart-block_row">
                                    <div class="Cart-block Cart-block_pict">
                                        <a class="Cart-pict" href="{% url 'products:product_detail' slug=i_item.seller_price.product.slug %}"><img class="Cart-img"
                                                                           src="{{ i_item.seller_price.product.images.first.image.url }}"
                                                                           alt="{{ i_item.seller_price.product.name }}"/></a>
                                    </div>
                                    <div class="Cart-block Cart-block_info">
                                        <a class="Cart-title" href="{% url 'products:product_detail' slug=i_item.seller_price.product.slug %}">{{ i_item.seller_price.product.name }}</a>
                                        <div class="Cart-desc">{{ i_item.seller_price.product.description }}</div>
                                    </div>
                                    <div class="Cart-block Cart-block_price">
                                        {% price_discount_order request i_item as price_set %}
                                        {% if price_set %}
                                            <div class="Card-priceOld">{{ price_set.old_price }}$
                                            </div>
                                            <div class="Cart-price">{{ price_set.discount_price }}$
                                            </div>
                                        {% else %}
                                            <div class="Cart-price">{{ i_item.sellerprice.price }}$
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="Cart-block Cart-block_row">
                                    <div class="Cart-block Cart-block_amount">{{ i_item.quantity }} шт.</div>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="Cart-total">
                                <div class="Cart-block Cart-block_total">
                                    <strong class="Cart-title">{% translate "Итого" %}:</strong>
                                    {% total_price request carts as price %}
                                    {% if price.old_price > config.FOR_PRICE and price.total_quantity > config.FOR_COUNT %}
                                        <span class="Card-priceOld">{{ price.old_price }}$</span>
                                        <span class="Cart-price">{{ price.total_price }}$</span>
                                        <div class="Cart-disc">
                                            {% if price.old_price > config.FOR_PRICE %}
                                            Ваша стоимость покупок в корзине составила более <b>{{ config.FOR_PRICE }}$</b>, для вас скидка составит <b>{{ price.full_percent }}%</b>
                                            {% else %}
                                            Ваше количество товаров в корзине более <b>{{ config.FOR_COUNT }} шт.</b>, для вас дополнительная скидка <b>{{ price.full_percent }}%</b>
                                            {% endif %}
                                        </div>
                                    {% elif price.old_price > config.FOR_PRICE %}
                                        <span class="Card-priceOld">{{ price.old_price }}$</span>
                                        <span class="Cart-price">{{ price.total_price }}$</span>
                                        <div class="Cart-disc">
                                            Ваша стоимость покупок в корзине составила более <b>{{ config.FOR_PRICE }}$</b>, для вас дополнительная скидка <b>{{ config.FOR_PRICE_PERCENT }}%</b>
                                        </div>
                                    {% elif price.total_quantity >  config.FOR_COUNT %}
                                        <span class="Card-priceOld">{{ price.old_price }}$</span>
                                        <span class="Cart-price">{{ price.total_price }}$</span>
                                        <div class="Cart-disc">
                                            Ваше количество товаров в корзине более <b>{{ config.FOR_COUNT }} шт.</b>, для вас дополнительная скидка <b>{{ config.FOR_COUNT_PERCENT }}%</b>
                                        </div>
                                    {% else %}
                                        <span class="Cart-price">{{ price.total_price }}$</span>
                                        <div class="Cart-disc">Если ваша стоимость покупок в корзине составит более <b>{{ config.FOR_PRICE }}$</b>, мы сделаем для вас скидку <b>{{ config.FOR_PRICE_PERCENT }}%</b></div>
                                        <div class="Cart-disc">Если количество купленного вами товара превысит <b>{{ config.FOR_COUNT }} шт.</b>, мы сделаем для вас скидку <b>{{ config.FOR_COUNT_PERCENT }}%</b></div>
                                        <div class="Cart-disc">Если будет выполнено два условия скидок на корзину, будет выбрано максимально выгодное предложение.</div>
                                    {% endif %}
                                </div>
                                {% if order.payment_status == 'unpaid' %}
                                <div class="Cart-block"><a class="btn btn_primary btn_lg"
                                                           href="{% url 'orders:order_payment' order.pk %}">{% translate "Оплатить" %}</a>
                                </div>
                                {% elif order.payment_status == 'error' %}
                                <div class="Cart-block">
                                    <a class="btn btn_primary btn_lg"
                                       href="{% url 'orders:order_payment' order.pk %}">{% translate "Оплатить снова" %}</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_marketplace/templates/templates_order/payment.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{% translate "Оплата" %}
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{% url 'home' %}">home</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate "Оплата" %}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <form class="form Payment" action="{% url 'orders:order_payment' pk=order.id %}" method="post">
                {% csrf_token %}
                <div class="Payment-card">
                    <div class="form-group">
                        <label class="form-label">{% translate "Номер карты" %}
                        </label>
                        <input class="form-input Payment-bill" id="card_number" name="card_number" type="text"
                               placeholder="9999 9999" data-mask="9999 9999"/>
                    </div>
                    {% if order.payment_option == 'someone' %}
                    <div class="form-group">
                        <button class="btn btn_success Payment-generate" href="#">{% translate "Сгенерировать случайный счет" %}</button>
                    </div>
                    {% endif %}
                </div>
                <button class="btn btn_primary" type="submit">{% translate "Оплатить" %}
                </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

django_marketplace/templates/templates_order/progress_payment.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<script>
    setTimeout(function() {
        window.location.href = "{% url 'home' %}";
    }, 5000);
</script>

<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{% translate "Ожидание оплаты" %}
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="index.html">home</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate "Ожидание оплаты" %}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section">
        <div class="wrap">
            <div class="ProgressPayment">
                <div class="ProgressPayment-title">{% translate "Ждем подтверждения оплаты платежной системой" %}
                </div>
                <div class="ProgressPayment-icon">
                    <div class="cssload-thecube">
                        <div class="cssload-cube cssload-c1"></div>
                        <div class="cssload-cube cssload-c2"></div>
                        <div class="cssload-cube cssload-c4"></div>
                        <div class="cssload-cube cssload-c3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}