django_marketplace/carts/urls.py
from django.urls import path

from .views import users_cart, delete_cart, add_cart, edit_cart

app_name = "carts"

urlpatterns = [
    path('cart/', users_cart, name='cart'),
    path('delete-cart/<int:cart_id>/', delete_cart, name='delete_cart'),
    path('add-cart/<int:sellerprice_id>/', add_cart, name='add_cart'),
    path('edit-cart/', edit_cart, name='edit_cart')
]

django_marketplace/comparisons/urls.py
from django.urls import path, include
from django.conf import settings

from .views_dir import *

app_name = 'comparisons'

urlpatterns = [
    path('', ComparisonListView.as_view(), name='comparison_list'),
    path('remove/<slug:slug>/', RemoveFromComparisonView.as_view(), name='remove_from_comparison'),
    path('add/<slug:slug>/', AddComparisonView.as_view(), name='add_to_comparison'),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include("debug_toolbar.urls")),
                  ] + urlpatterns

django_marketplace/core/urls.py
"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views_dir. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views_dir
    1. Add an import:  from my_app import views_dir
    2. Add a URL to urlpatterns:  path('', views_dir.home, name='home')
Class-based views_dir
    1. Add an import:  from other_app.views_dir import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from products.views import HomeView


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='admin'),
    path('product/', include('products.urls')),
    path('order/', include('orders.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('carts.urls')),
    path('', HomeView.as_view(), name='home'),
    path('comparison/', include('comparisons.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

django_marketplace/products/urls.py
from django.urls import path, include
from django.conf import settings
from .views import *
from .views_dir import SaleView

app_name = "products"

urlpatterns = [
    path('discounts/', DiscountListView.as_view(), name='discounts_list'),
    path('catalog/', ProductsListView.as_view(), name="products_list"),
    path('catalog/sale/', SaleView.as_view(), name='sale_list'),
    path('<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    path('add-review/<slug:slug>/', ReviewCreateView.as_view(), name='review_create'),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include("debug_toolbar.urls")),
                  ] + urlpatterns

django_marketplace/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .views_dir import (
    AccountView,
    ProfileView,
    UserOrderHistoryView,
    RegisterView,
    UserPasswordResetView,
    LoginUser,
    LogoutUser,
    get_viewed_products,
    get_viewed_count,
    remove_product_from_viewed,
)

app_name = "user"

urlpatterns = [
    path('login/',
         LoginUser.as_view(
             template_name='templates_users/login.html',
             redirect_authenticated_user=True,
             extra_context={'simple_header': True},
         ),
         name="login"
         ),

    path('logout/',
         LogoutUser.as_view(
             next_page=reverse_lazy("home"),
         ),
         name="logout"
         ),

    path('register/',
         RegisterView.as_view(),
         name='register'
         ),

    path('account/',
         AccountView.as_view(),
         name='account'
         ),

    path('account/profile/',
         ProfileView.as_view(),
         name='user_profile'
         ),

    path('account/order_history/',
         UserOrderHistoryView.as_view(),
         name='user_order_history',
         ),

    path('password-reset/',
         UserPasswordResetView.as_view(),
         name="password_reset"
         ),

    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="templates_users/password_reset_confirm.html",
             success_url=reverse_lazy("user:password_reset_complete"),
             extra_context={'simple_header': True},
         ),
         name="password_reset_confirm",
         ),

    path(
        'password-reset-complete/',
        PasswordResetCompleteView.as_view(
            template_name="templates_users/password_reset_complete.html",
            extra_context={'simple_header': True},
        ),
        name="password_reset_complete",
    ),

    path('viewed/remove/<int:product_id>/',
         remove_product_from_viewed,
         name='remove_product_from_viewed'
         ),

    path('viewed/count/',
         get_viewed_count,
         name='get_viewed_count'
         ),

    path('viewed-products/',
         get_viewed_products,
         name='viewed_products'
         ),
]

django_marketplace/templates/templates_products/discounts_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block header %}
<!-- Здесь будет header -->
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Section">
        <div class="wrap">
            <div class="Cards Cards_blog">
                {% for discount in discounts %}
                <div class="Card">
                    <div class="Card-content">
                        <strong class="Card-title"><a href="{% url 'products:products_list' %}?discount={{ discount.id }}">{{ discount.description }}</a></strong>
                        <div class="Card-description">
                            {% translate "Скидка" %}: {{ discount.percent }}% <br>
                            {% translate "Действует с" %} {{ discount.from_date|date:"d.m.Y" }} {% translate "по" %} {{ discount.to_date|date:"d.m.Y" }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
<!-- Здесь будет footer -->
{% endblock %}

django_marketplace/templates/templates_products/product_template.html
{% extends 'base.html' %}
{% load static %}
{% load mptt_tags %}
{% load cache %}
{% load i18n %}
{% load products_tags %}
{% block title %} Product {{ product.pk }} {% endblock %}

{% block header %}
<!-- Здесь будет header -->
{% endblock %}

{% block content %}
{% cache 1 product_detail %}
<div class="Middle Middle_top">
    <div class="Section">
        <div class="wrap">
            <div class="Product">
                <div class="ProductCard">
                    <div class="ProductCard-look">
                        {% if product.discount %}
                        {% get_discount product.discount as best_discount %}
                        <div class="Card-date">
                            <strong class="Card-date-number">{{ best_discount.percent }}%
                            </strong><span class="Card-date-month">{{ best_discount.from_date }}</span>
                        </div>
                        {% endif %}
                        <div class="ProductCard-photo">
                            {% if first_image.image.url %}
                            <img src="{{ first_image.image.url }}" alt="{{ product.name }}">
                            {% endif %}
                        </div>
                        <div class="ProductCard-picts">
                            {% for img in product.images.all %}
                            <a class="ProductCard-pict {% if forloop.first %} ProductCard-pict_ACTIVE{% endif %}"
                               href="{{ img.image.url }}"><img src="{{ img.image.url }}"
                                                               alt="{{ product.name }}"/></a>
                            {% empty %}
                            <p>{% translate "Еще нету изображения" %}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="ProductCard-desc">
                        <div class="ProductCard-header">
                            <h2 class="ProductCard-title">{{ product.name }}</h2>
                            <div class="ProductCard-info">

                                <div class="ProductCard-cost">
                                    <div class="ProductCard-price">
                                        {% if product.discount %}
                                        {% solve_price product.auto_seller_price|floatformat:0 best_discount as disk %}
                                        <span class="Card-priceOld">{{ disk.old_price }}$</span>
                                        <span>{{ disk.dis }}$</span>
                                        {% else %}
                                        <span>${{ product.auto_seller_price|floatformat:0 }}</span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="ProductCard-text">
                            <ul>
                                {% for line in description_short %}
                                <li>{{ line }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="ProductCard-cart">
                            {% if product.seller_price.first %}
                            <form action="{% url 'carts:add_cart' product.seller_price.first.id %}"
                                  method="post" style="display: flex; margin-right: 15px;">
                                {% csrf_token %}
                                <div class="ProductCard-cartElement ProductCard-cartElement_amount">
                                    <div class="Amount Amount_product">
                                        <button class="Amount-remove" type="button"></button>
                                        <input class="Amount-input form-input" name="amount" type="text"
                                               value="1"/>
                                        <button class="Amount-add" type="button"></button>
                                    </div>
                                </div>
                                <div class="ProductCard-cartElement">
                                    <button class="btn btn_primary Amount-input form-input" type="submit">
                                        <img class="btn-icon"
                                             src="{% static 'img/icons/card/cart_white.svg' %}"
                                             alt="cart_white.svg"/>
                                        <span class="btn-content">{% translate "Купить" %}</span>
                                    </button>
                                </div>
                            </form>
                            {% endif %}
                            <div class="ProductCard-cartElement">
                                <form method="post"
                                      action="{% url 'comparisons:add_to_comparison' slug=product.slug %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn_primary">
                                        {% translate "Добавить в сравнение" %}
                                    </button>
                                </form>
                            </div>
                            <div id="modal_open" class="my_modal">
                                <div class="my_modal-dialog">
                                    <div class="my_modal-content">
                                        <div class="my_modal-header">
                                            <p class="my_modal-title">{% translate "Поздравляем!" %}</p>
                                            <a href="#" title="{% translate 'Закрыть модальное окно' %}"
                                               class="close">×</a>
                                        </div>
                                        <div class="my_modal-body">
                                            <p>{% translate "Товар успешно добавлен в корзину!" %}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="ProductCard-footer">
                            <div class="ProductCard-tags">
                                <strong class="ProductCard-tagsTitle">{% translate "Тэги" %}:</strong>
                                {% for tag in product.tags.all %}
                                <a href="#">{{ tag.name }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Tabs Tabs_default">
                    <div class="Tabs-links">
                        <a class="Tabs-link_ACTIVE Tabs-link" href="#description">
                            <span>{% translate "Описание" %}</span>
                        </a>
                        <a class="Tabs-link" href="#sellers">
                            <span>{% translate "Продавцы" %}</span>
                        </a>
                        <a class="Tabs-link" href="#addit">
                            <span>{% translate "Характеристика" %}</span>
                        </a>
                        <a class="Tabs-link" href="#reviews">
                            <span>{% translate "Отзывы" %}</span>
                        </a>
                    </div>
                    <div class="Tabs-wrap">
                        <div class="Tabs-block" id="description">
                            <h2>{{ product.name }}</h2>
                            <p>
                                <img class="pict pict_right" src="{{ first_image.image.url }}"
                                     alt="{{ product.name }}">
                            </p>
                            <ul>
                                {% for des in description_full %}
                                <li>{{ des }}</li>
                                {% endfor %}
                            </ul>
                            <div class="clearfix"></div>
                            <div class="table">
                                <table>
                                    <tr>
                                        <th>{% translate "Характеристика" %}</th>
                                        <th>{% translate "Значение" %}</th>
                                    </tr>
                                    <tr>
                                        <td>{% translate "Тип товара" %}</td>
                                        <td>{{ product.category.name }}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>

                        <div class="Tabs-block" id="sellers">
                            <div class="Section-content">
                                <div class="Orders">
                                    {% for sp in product.seller_price.all %}
                                    <div class="Order Order_anons">
                                        <div class="Order-personal">
                                            <div class="row">
                                                <div class="row-block">
                                                    <a class="Order-title" href="#">
                                                        {% translate "Имя продавца" %}: {{ sp.seller.name }}
                                                    </a>
                                                    <div class="ProductCard-cartElement"
                                                         style="margin-top: 10px;">
                                                        <a class="btn btn_primary"
                                                           href="{% url 'carts:add_cart' sp.id %}">
                                                            <img class="btn-icon"
                                                                 src="{% static 'img/icons/card/cart_white.svg' %}"
                                                                 alt="cart_white.svg"/>
                                                            <span class="btn-content">{% translate "Купить" %}</span>
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="row-block">
                                                    <div class="Order-info Order-info_delivery">
                                                        <div class="Order-infoType">{% translate "Тип доставки" %}:
                                                        </div>
                                                        <div class="Order-infoContent">{% translate "Обычная доставка"%}
                                                        </div>
                                                    </div>
                                                    <div class="Order-info Order-info_pay">
                                                        <div class="Order-infoType">{% translate "Оплата" %}:</div>
                                                        <div class="Order-infoContent">{% translate "Онлайн картой" %}
                                                        </div>
                                                    </div>
                                                    <div class="Order-info">
                                                        <div class="Order-infoType">{% translate "Стоимость" %}:</div>
                                                        <div class="Order-infoContent">
                                                            {% if sp.price %}
                                                            <span class="Order-price">{{ sp.price }}$</span>
                                                            {% else %}
                                                            <span class="Order-price">Цена товара не задана</span>
                                                            {% endif %}

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="Tabs-block" id="addit">
                            <div class="Product-props">
                                {% for f in product.features.all %}
                                <div class="Product-prop">
                                    <strong>{{ f.feature.name }}</strong><span>{{ f.value }}</span>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="Tabs-block" id="reviews">
                            {% include 'templates_products/review_product.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endcache %}
{% endblock %}

{% block footer %}
<!-- Здесь будет footer -->
{% endblock %}

django_marketplace/templates/templates_products/review_product.html
{% load i18n %}

{% if reviews %}
{% for review in reviews %}
<div class="Comments">
    <div class="Comment">
        <div class="Comment-column Comment-column_pict">
            <div class="Comment-avatar">
            </div>
        </div>
        <div class="Comment-column">
            <header class="Comment-header">
                <div>
                    <strong class="Comment-title">{{ review.user }}</strong>
                    <span class="Comment-date">{% translate "Дата" %}: {{ review.date|date:"d.m.Y H:i" }}</span>
                </div>
            </header>
            <div class="Comment-content">{{ review.comment }}</div>
        </div>
    </div>
</div>
{% endfor %}
{% if reviews.has_other_pages %}
<div class="pagination">
    <span class="step-links">
        {% if reviews.has_previous %}
            <a href="?page={{ reviews.previous_page_number }}">« {% translate "Предыдущая" %}</a>
        {% endif %}
        <span class="current">
            {% translate "Страница" %} {{ reviews.number }} {% translate "из" %} {{ reviews.paginator.num_pages }}.
        </span>
        {% if reviews.has_next %}
            <a href="?page={{ reviews.next_page_number }}">{% translate "Следующая" %} »</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% else %}
<p>{% translate "Пока отзывов нет. Будьте первым, кто оставит отзыв!" %}</p>
{% endif %}


{% if user.is_authenticated %}
    <header class="Section-header Section-header_product">
        <h3 class="Section-title">{% translate "Добавить отзыв" %}
        </h3>
    </header>
<div class="Tabs-addComment">
    <form class="form" action="{% url 'products:review_create' slug=product.slug %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
            <textarea class="form-textarea" name="comment" placeholder="{% translate 'Отзыв' %}"></textarea>
        </div>
        <div class="form-group">
            <button class="btn btn_muted" type="submit">{% translate "Отправить отзыв" %}</button>
        </div>
    </form>
</div>
{% else %}
<p>{% translate "Только зарегистрированные пользователи могут оставлять отзывы. Пожалуйста, войдите в аккаунт или зарегеструруйтесь." %}</p>
<a class="btn btn_primary" href="{% url 'user:login' %}">{% translate 'Вход' %}</a>
<a class="btn btn_primary" href="{% url 'user:register' %}">{% translate 'Регистрация' %}</a>
{% endif %}

django_marketplace/templates/templates_products/sale_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load cache %}

{% block title %} Товары со скидкой {% endblock %}

{% block header %}
<!-- Здесь будет header -->
{% endblock %}

{% block content %}
{% cache config.CACHES_PRODUCTS sale_list %}
{% if products %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Sort">
                        <div class="Sort-title">{% translate "Скидка" %}:</div>
                        <div class="Sort-variants">
                            <div>
                                <a href="?sort=discount_desc">{% translate "По убыванию" %}</a>
                            </div>
                            <div style="display:inline; margin: 0 10px;">
                                <a href="?sort=discount_asc">{% translate "По возрастанию" %}</a>
                            </div>
                        </div>
                    </div>
                    <div class="Cards">
                        {% for product in products %}
                            {% with product.images.all|first as img %}
                                <div class="Card">
                                    <a class="Card-picture" href="{{ product.get_absolute_url }}">
                                        <img src="{{ img.image.url }}" alt="{{ product.name }}" />
                                    </a>
                                    <div class="Card-content">
                                        <strong class="Card-title">
                                            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                        </strong>
                                        <div class="Card-description">

                                            <div class="Card-category">
                                                {{ product.category.name }}
                                            </div>
                                            <div class="Card-hover">
                                                <a class="Card-btn" href="{% url 'carts:add_cart' product.seller_price.first.id %}">
                                                    <img src="{% static 'img/icons/card/cart.svg' %}" alt="cart.svg" />
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endwith %}
                        {% endfor %}
                    </div>
                    {% if page_obj.has_other_pages %}
                        <div class="Pagination">
                            <div class="Pagination-ins">
                                {% if page_obj.has_previous %}
                                    <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.previous_page_number }}">
                                        <img src="{% static 'img/icons/prevPagination.svg' %}" alt="prevPagination.svg"/>
                                    </a>
                                {% endif %}
                                {% for p in paginator.page_range %}
                                    {% if page_obj.number == p %}
                                        <span class="Pagination-element Pagination-element_prev Pagination-text">{{ p }}</span>
                                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                                        <a class="Pagination-element Pagination-element_current" href="?page={{ p }}">
                                            <span class="Pagination-text">{{ p }}</span></a>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <a class="Pagination-element Pagination-element_prev" href="?page={{ page_obj.next_page_number }}">
                                        <img src="{% static 'img/icons/nextPagination.svg' %}" alt="nextPagination.svg"/>
                                    </a>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% else %}
    <p>{% translate "Пока товаров нет." %}</p>
{% endif %}
{% endcache %}
{% endblock %}

{% block footer %}
<!-- Здесь будет footer -->
{% endblock %}