django_marketplace/core/urls.py
"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views_dir. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views_dir
    1. Add an import:  from my_app import views_dir
    2. Add a URL to urlpatterns:  path('', views_dir.home, name='home')
Class-based views_dir
    1. Add an import:  from other_app.views_dir import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from products.views import HomeView


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='admin'),
    path('product/', include('products.urls')),
    path('order/', include('orders.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('carts.urls')),
    path('', HomeView.as_view(), name='home'),
    path('comparison/', include('comparisons.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

django_marketplace/orders/urls.py
from django.urls import path
from .views_dir import OrderProcessView, OrderPaymentView, ProgressPaymentView, OrderDetailView

app_name = "orders"

urlpatterns = [
    path('order=<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('proceed/', OrderProcessView.as_view(), name='order_proceed'),
    path('proceed/<int:pk>/payment', OrderPaymentView.as_view(), name='order_payment'),
    path('proceed/<int:pk>/payment_progress', ProgressPaymentView.as_view(), name='payment_progress'),
]

django_marketplace/products/urls.py
from django.urls import path, include
from django.conf import settings
from .views import *
from .views_dir import SaleView

app_name = "products"

urlpatterns = [
    path('discounts/', DiscountListView.as_view(), name='discounts_list'),
    path('catalog/', ProductsListView.as_view(), name="products_list"),
    path('catalog/sale/', SaleView.as_view(), name='sale_list'),
    path('<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    path('add-review/<slug:slug>/', ReviewCreateView.as_view(), name='review_create'),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include("debug_toolbar.urls")),
                  ] + urlpatterns

django_marketplace/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .views_dir import (
    AccountView,
    ProfileView,
    UserOrderHistoryView,
    RegisterView,
    UserPasswordResetView,
    LoginUser,
    LogoutUser,
    get_viewed_products,
    get_viewed_count,
    remove_product_from_viewed,
)

app_name = "user"

urlpatterns = [
    path('login/',
         LoginUser.as_view(
             template_name='templates_users/login.html',
             redirect_authenticated_user=True,
             extra_context={'simple_header': True},
         ),
         name="login"
         ),

    path('logout/',
         LogoutUser.as_view(
             next_page=reverse_lazy("home"),
         ),
         name="logout"
         ),

    path('register/',
         RegisterView.as_view(),
         name='register'
         ),

    path('account/',
         AccountView.as_view(),
         name='account'
         ),

    path('account/profile/',
         ProfileView.as_view(),
         name='user_profile'
         ),

    path('account/order_history/',
         UserOrderHistoryView.as_view(),
         name='user_order_history',
         ),

    path('password-reset/',
         UserPasswordResetView.as_view(),
         name="password_reset"
         ),

    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="templates_users/password_reset_confirm.html",
             success_url=reverse_lazy("user:password_reset_complete"),
             extra_context={'simple_header': True},
         ),
         name="password_reset_confirm",
         ),

    path(
        'password-reset-complete/',
        PasswordResetCompleteView.as_view(
            template_name="templates_users/password_reset_complete.html",
            extra_context={'simple_header': True},
        ),
        name="password_reset_complete",
    ),

    path('viewed/remove/<int:product_id>/',
         remove_product_from_viewed,
         name='remove_product_from_viewed'
         ),

    path('viewed/count/',
         get_viewed_count,
         name='get_viewed_count'
         ),

    path('viewed-products/',
         get_viewed_products,
         name='viewed_products'
         ),
]

django_marketplace/users/views/account.py
from django.views.generic import TemplateView


class AccountView(TemplateView):
    """
    Личный кабинет пользователя
    необходимо доработать
    """
    template_name = 'templates_users/account.html'

django_marketplace/templates/templates_users/account.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% translate "Личный кабинет" %}
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="{% url 'home' %}">home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate "Личный кабинет" %}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        {% include 'templates_users/user_account_navigation.html' %}
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Account">
                        <div class="Account-group">
                            <div class="Account-column">
                                {% if user.profile_picture %}
                                    <div class="Account-avatar"><img src="{{ user.profile_picture.url }}" alt="profile_picture" />
                                </div>
                                {% else %}
                                    <div class="Account-avatar">{% translate "Изображение недоступно" %}</div>
                                {% endif %}
                            </div>
                            <div class="Account-column">
                                <div class="Account-name"> {{ user.first_name }} {{ user.last_name }}
                                </div><a class="Account-editLink" href="{% url 'user:user_profile' %}">{% translate "Редактировать профиль" %}</a>
                            </div>
                        </div>
                        <div class="Account-group">
                            <div class="Account-column Account-column_full">
                                <div class="Order Order_anons">
                                    {% if order %}
                                        <div class="Order-personal">
                                        <div class="row">
                                            <div class="row-block"><a class="Order-title" href="{% url 'orders:order_detail' pk=order.id %}">{% translate "Заказ" %}&#32;<span class="Order-numberOrder">№{{ order.id }}</span>&#32;от&#32;<span class="Order-dateOrder">{{ order.created_at|date:"d.m.Y" }}</span></a>
                                                <div class="Account-editLink"><a href="{% url 'user:user_order_history' %}">{% translate "История заказов" %}</a>
                                                </div>
                                            </div>
                                            <div class="row-block">
                                                <div class="Order-info Order-info_delivery">
                                                    <div class="Order-infoType">{% translate "Тип доставки" %}:
                                                    </div>
                                                    <div class="Order-infoContent">{% translate order.get_delivery_label %}
                                                    </div>
                                                </div>
                                                <div class="Order-info Order-info_pay">
                                                    <div class="Order-infoType">{% translate "Оплата" %}:
                                                    </div>
                                                    <div class="Order-infoContent">{% translate order.get_payment_label %}
                                                    </div>
                                                </div>
                                                <div class="Order-info">
                                                    <div class="Order-infoType">{% translate "Итого" %}:
                                                    </div>
                                                    <div class="Order-infoContent"><span class="Order-price">{{ order.total_price }}$</span>
                                                    </div>
                                                </div>
                                                <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{% translate "Статус" %}:
                                            </div>
                                            {% if order.payment_status == "paid" %}
                                                <div class="Order-infoContent">{% translate order.get_payment_status_label %}
                                                </div>
                                            {% else %}
                                                <a class="Order-infoContent" href="{% url 'orders:order_payment' pk=order.id %}">{% translate order.get_payment_status_label %}
                                                </a>
                                            {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% translate "Ожидает обработки" %}
                                    {% else %}
                                        {% translate "У вас еще нет заказов" %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

django_marketplace/templates/templates_users/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	{% translate "Авторизация" %}
{% endblock %}

{% block content %}
    <main class="Middle">
      <div class="wrapper">
        <div class="header">
            <h3 class="sign-in">{% translate "Вход" %}</h3>
        </div>
        <div class="clear"></div>
        <form method="post">
            {% csrf_token %}
            <div>
                <input class="user-input" type="email" name="username" id="name" placeholder="E-mail" />
            </div>
            <div class="form-error">
                <strong>{{ form.username.errors }}</strong>
            </div>
            <div>
                <input type="password" name="password" id="name" placeholder="*********" />
            </div>
            <div class="form-error">
                <strong>{{ form.password.errors }}</strong>
            </div>
            <div>
                <input type="submit" value="{% translate 'Войти' %}" />
            </div>
            <a class="forgot-label" href="{% url 'user:password_reset' %}">{% translate "Забыли пароль" %}?</a>
            <a class="registr" href="{% url 'user:register' %}">{% translate "Регистрация" %}</a>
        </form>
        {% if form.non_field_errors %}
            <div class="form-error">{% translate "Вы ввели неверные данные" %}</div>
        {% endif %}
      </div>
    </main>
{% endblock %}

django_marketplace/templates/templates_users/password_reset.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	{% translate "Восстановление пароля" %} (1)
{% endblock %}

    {% if messages %}
        <div class="messages">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
                {{ message }}
            </div>
        {% endfor %}
        </div>
    {% endif %}

{% block content %}
    <div class="wrapper">
        <div class="header">
            <h3 class="sign-in">{% translate "Восстановление пароля" %} (1/2)</h3>
            <h5>
                {% translate "Для восстановления пароля введите адрес электронной почты, на которую зарегистрирована учетная запись" %}
            </h5>
        </div>
        <form method="post">
            {% csrf_token %}
            <div>
                <input class="user-input" type="email" name="email" id="name" placeholder="E-mail" />
            </div>
                <div class="form-error">
                    <strong>{{ form.email.errors }}</strong>
                </div>
            <div>
                <input type="submit" value="{% translate 'Получить ссылку для восстановления' %}" />
            </div>
            <a class="registr" href={% url 'user:login' %}>
                {% translate "Вход" %}
            </a>
        </form>
    </div>
{% endblock %}

django_marketplace/templates/templates_users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	{% translate "Восстановление пароля" %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="header">
            <h3 class="sign-in">{% translate "Восстановление пароля" %}</h3>
            <p>
                {% translate "Новый пароль установлен. Вы можете пройти по ссылке" %}
                <a class="registr" href="{% url 'user:login' %}">{% translate "Вход" %}</a>
            </p>
        </div>
    </div>
{% endblock %}

django_marketplace/templates/templates_users/password_reset_confirm.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	{% translate "Восстановление пароля" %} (2)
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="header">
            <h3 class="sign-in">{% translate "Восстановление пароля" %} (2/2)</h3>
            <h5>{% translate "Придумайте новый пароль для учетной записи" %}</h5>
        </div>

        <form method="post">
          {% csrf_token %}
            <div>
                <input type="password" name="new_password1" id="name" placeholder="Пароль" />
                <div class="form-error">
                    <strong>{{ form.new_password2.errors }}</strong>
                </div>
            </div>
            <div>
                <input type="password" name="new_password2" id="name" placeholder="{% translate 'Повторить пароль' %}" />
            </div>
            <div>
                <input type="submit" value="{% translate 'Сохранить пароль' %}"/>
            </div>
        </form>
    </div>
    {% if form.non_field_errors %}
        <div class="form-error">{% translate "Вы ввели неверные данные" %}</div>
    {% endif %}

{% endblock %}

django_marketplace/templates/templates_users/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} MEGANO SHOP Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  MEGANO SHOP
{% endautoescape %}

django_marketplace/templates/templates_users/products_history.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load mptt_tags %}
{% load cache %}

{% block title %} Product {{ product.pk }} {% endblock %}

{% block header %}
<!-- Здесь будет header -->
{% endblock %}

{% block content %}
<div class="Middle Middle_top">
    <div class="Middle-top">
        <div class="wrap">
            <div class="Middle-header">
                <h1 class="Middle-title">{% translate "Личный кабинет" %}
                </h1>
                <ul class="breadcrumbs Middle-breadcrumbs">
                    <li class="breadcrumbs-item"><a href="{% url 'home' %}">home</a>
                    </li>
                    <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate "Личный кабинет" %}</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="Section Section_column Section_columnLeft">
        <div class="wrap">
            <div class="Section-column">
                <div class="Section-columnSection">
                    {% include 'templates_users/user_account_navigation.html' %}
                </div>
            </div>
            <div class="Section-content">
                <h1>{% translate "История просмотров товаров" %}</h1>
                <div class="Cards">
                    <ul>
                        {% if products %}
                        {% for product in products %}
                        <li>
                            <div class="Card-content">
                                <strong class="Card-title"><a
                                        href="{% url 'products:product_detail' slug=product.productslug %}">
                                    {{ product.productname }}</a>
                                </strong>
                                {% with product.images.all|first as img %}
                                <div class="Card"><a class="Card-picture"
                                                     href="{% url 'products:product_detail' slug=product.productslug %}"><img
                                        src="{{ img.image.url }}" alt="card.jpg"/></a>
                                    {% endwith %}
                                    <div class="Card-description">
                                        <div class="Card-category">{{ product.productcategory }}</div>
                                    </div>
                        </li>
                        {% endfor %}
                        {% else %}
                        <li>{% translate "История просмотров пуста." %}</li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}
<!-- Здесь будет footer -->
{% endblock %}

django_marketplace/templates/templates_users/register.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
	{% translate "Регистрация" %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="header">
            <h3 class="sign-in">{% translate "Регистрация" %}</h3>
        </div>
        <div class="clear"></div>
        <form method="post">
            {% csrf_token %}
            <div>
                <input class="user-input" type="text" name="first_name" id="name" placeholder="Имя" />
                <div class="form-error">
                    <strong>{{ form.first_name.errors }}</strong>
                </div>
            </div>
            <div>
                <input class="user-input" type="email" name="email" id="name" placeholder="E-mail" />
                <div class="form-error">
                    <strong>{{ form.email.errors }}</strong>
                </div>
            </div>
            <div>
                <input type="password" name="password1" id="name" placeholder="{% translate 'Пароль' %}" />
            </div>
            <div class="form-error">
                <strong>{{ form.password2.errors }}</strong>
            </div>
            <div>
                <input type="password" name="password2" id="name" placeholder="{% translate 'Повторить пароль' %}"/>
            </div>
            <input type="submit" value="{% translate 'Зарегистрироваться' %}"/>
            <a class="registr" href="{% url 'user:login' %}">
                {% translate "Вход" %}
            </a>
            <div class="clear"></div>
        </form>
        {% if form.non_field_errors %}
            <div class="form-error">{% translate "Вы ввели неверные данные" %}</div>
        {% endif %}
  </div>
{% endblock %}

django_marketplace/templates/templates_users/user_account_navigation.html
{% load i18n %}

<header class="Section-header">
    <strong class="Section-title">{% translate "Навигация" %}
    </strong>
</header>
<div class="Section-columnContent">
    <div class="NavigateProfile">
        {% url 'user:account' as account_url %}
        {% url 'user:user_profile' as profile_url %}
        {% url 'user:user_order_history' as order_history_url %}
        {% url 'user:viewed_products' as viewed_products_url %}
        <ul class="menu menu_vt">
            <li class="menu-item {% if request.path == account_url %}menu-item_ACTIVE{% endif %}">
                <a class="menu-link" href="{% url 'user:account' %}">{% translate "Личный кабинет" %}</a>
            </li>
            <li class="menu-item {% if request.path == profile_url %}menu-item_ACTIVE{% endif %}">
                <a class="menu-link" href="{% url 'user:user_profile' %}">{% translate "Профиль" %}</a>
            </li>
            <li class="menu-item {% if request.path == order_history_url %}menu-item_ACTIVE{% endif %}">
                <a class="menu-link" href="{% url 'user:user_order_history' %}">{% translate "История заказов" %}</a>
            </li>
            <li class="menu-item {% if request.path == viewed_products_url %}menu-item_ACTIVE{% endif %}">
                <a class="menu-link" href="{% url 'user:viewed_products' %}">{% translate "История просмотров" %}</a>
            </li>
        </ul>
    </div>
</div>

django_marketplace/templates/templates_users/user_order_history.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% translate "Личный кабинет" %}
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="{% url 'home' %}">home</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% translate "История заказов" %}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        {% include 'templates_users/user_account_navigation.html' %}
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Orders">
                        {% if orders %}
                        {% for i_order in orders %}
                        <div class="Order Order_anons">
                            <div class="Order-personal">
                                <div class="row">
                                    <div class="row-block"><a class="Order-title" href="{% url 'orders:order_detail' pk=i_order.id %}">{% translate "Заказ" %}&#32;<span class="Order-numberOrder">№{{ i_order.id }}</span>&#32;{% translate "от" %}&#32;<span class="Order-dateOrder">{{ i_order.created_at|date:"d.m.Y" }}</span></a>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">{% translate "Тип доставки" %}:
                                            </div>
                                            <div class="Order-infoContent">{% translate i_order.get_delivery_label %}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">{% translate "Оплата" %}:
                                            </div>
                                            <div class="Order-infoContent">{% translate i_order.get_payment_label %}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% translate "Общая стоимость" %}:
                                            </div>
                                            <div class="Order-infoContent"><span class="Order-price">{{ i_order.total_price }}$</span>
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{% translate "Статус" %}:
                                            </div>
                                            {% if i_order.payment_status == "paid" %}
                                                <div class="Order-infoContent">{% translate i_order.get_payment_status_label %}
                                                </div>
                                            {% else %}
                                                <a class="Order-infoContent" href="{% url 'orders:order_payment' pk=i_order.id %}">{% translate i_order.get_payment_status_label %}
                                                </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% else %}
                            {% translate "У тебя еще пока нет заказов" %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}