django_marketplace/carts/urls.py
from django.urls import path

from .views import users_cart, delete_cart, add_cart, edit_cart

app_name = "carts"

urlpatterns = [
    path('cart/', users_cart, name='cart'),
    path('delete-cart/<int:cart_id>/', delete_cart, name='delete_cart'),
    path('add-cart/<int:sellerprice_id>/', add_cart, name='add_cart'),
    path('edit-cart/', edit_cart, name='edit_cart')
]

django_marketplace/comparisons/urls.py
from django.urls import path, include
from django.conf import settings

from .views_dir import *

app_name = 'comparisons'

urlpatterns = [
    path('', ComparisonListView.as_view(), name='comparison_list'),
    path('remove/<slug:slug>/', RemoveFromComparisonView.as_view(), name='remove_from_comparison'),
    path('add/<slug:slug>/', AddComparisonView.as_view(), name='add_to_comparison'),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include("debug_toolbar.urls")),
                  ] + urlpatterns

django_marketplace/core/urls.py
"""
URL configuration for core project.

The `urlpatterns` list routes URLs to views_dir. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views_dir
    1. Add an import:  from my_app import views_dir
    2. Add a URL to urlpatterns:  path('', views_dir.home, name='home')
Class-based views_dir
    1. Add an import:  from other_app.views_dir import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from products.views import HomeView


urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls, name='admin'),
    path('product/', include('products.urls')),
    path('order/', include('orders.urls')),
    path('user/', include('users.urls')),
    path('cart/', include('carts.urls')),
    path('', HomeView.as_view(), name='home'),
    path('comparison/', include('comparisons.urls')),
    path('i18n/', include('django.conf.urls.i18n'))
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

django_marketplace/products/urls.py
from django.urls import path, include
from django.conf import settings
from .views import *
from .views_dir import SaleView

app_name = "products"

urlpatterns = [
    path('discounts/', DiscountListView.as_view(), name='discounts_list'),
    path('catalog/', ProductsListView.as_view(), name="products_list"),
    path('catalog/sale/', SaleView.as_view(), name='sale_list'),
    path('<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    path('add-review/<slug:slug>/', ReviewCreateView.as_view(), name='review_create'),
]

if settings.DEBUG:
    urlpatterns = [
                      path('__debug__/', include("debug_toolbar.urls")),
                  ] + urlpatterns

django_marketplace/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .views_dir import (
    AccountView,
    ProfileView,
    UserOrderHistoryView,
    RegisterView,
    UserPasswordResetView,
    LoginUser,
    LogoutUser,
    get_viewed_products,
    get_viewed_count,
    remove_product_from_viewed,
)

app_name = "user"

urlpatterns = [
    path('login/',
         LoginUser.as_view(
             template_name='templates_users/login.html',
             redirect_authenticated_user=True,
             extra_context={'simple_header': True},
         ),
         name="login"
         ),

    path('logout/',
         LogoutUser.as_view(
             next_page=reverse_lazy("home"),
         ),
         name="logout"
         ),

    path('register/',
         RegisterView.as_view(),
         name='register'
         ),

    path('account/',
         AccountView.as_view(),
         name='account'
         ),

    path('account/profile/',
         ProfileView.as_view(),
         name='user_profile'
         ),

    path('account/order_history/',
         UserOrderHistoryView.as_view(),
         name='user_order_history',
         ),

    path('password-reset/',
         UserPasswordResetView.as_view(),
         name="password_reset"
         ),

    path('password-reset-confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name="templates_users/password_reset_confirm.html",
             success_url=reverse_lazy("user:password_reset_complete"),
             extra_context={'simple_header': True},
         ),
         name="password_reset_confirm",
         ),

    path(
        'password-reset-complete/',
        PasswordResetCompleteView.as_view(
            template_name="templates_users/password_reset_complete.html",
            extra_context={'simple_header': True},
        ),
        name="password_reset_complete",
    ),

    path('viewed/remove/<int:product_id>/',
         remove_product_from_viewed,
         name='remove_product_from_viewed'
         ),

    path('viewed/count/',
         get_viewed_count,
         name='get_viewed_count'
         ),

    path('viewed-products/',
         get_viewed_products,
         name='viewed_products'
         ),
]

django_marketplace/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html id="get-page" lang="ru">
<head>
    <meta charset="utf-8">
    <title>{% block title %} Megano {% endblock %}</title>
    <meta name="description" content="{% translate 'Описание страницы' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'fonts/Roboto/Roboto-Regular.woff' %}" as="font">
    <link rel="preload" href="{% static 'fonts/Roboto/Roboto-Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'fonts/Roboto/Roboto-Bold.woff' %}" as="font">
    <link rel="preload" href="{% static 'fonts/Roboto/Roboto-Bold_Italic.woff' %}" as="font">
    <link rel="preload" href="{% static 'fonts/Roboto/Roboto-Light.woff' %}" as="font">
    <link rel="preload" href="{% static 'fonts/Roboto/Roboto-Light_Italic.woff' %}" as="font">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/basic.css' %}">
    <link rel="stylesheet" href="{% static 'css/extra.css' %}">
</head>

<body>

{% include 'header.html' %}

{% block content %}
<!-- Основное содержимое страницы -->
{% endblock %}

{% include 'footer.html' %}

<script src="{% static 'plg/CountDown/countdown.js' %}"></script>
<script src="{% static 'plg/jQuery/jquery-3.5.0.slim.min.js' %}"></script>
<script src="{% static 'plg/form/jquery.form.js' %}"></script>
<script src="{% static 'plg/form/jquery.maskedinput.min.js' %}"></script>
<script src="{% static 'plg/range/ion.rangeSlider.min.js' %}"></script>
<script src="{% static 'plg/Slider/slick.min.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
{% block extra_scripts %}

{% endblock %}
</body>
</html>

django_marketplace/templates/footer.html
{% load static %}
{% load i18n %}

<footer class="Footer">
    <div class="wrap">
        <div class="row Footer-main">
            <div class="row-block">
                <a class="logo Footer-logo" href="index.html">
                    <img class="logo-image" src="{% static 'img/logo_footer.png' %}" alt="logo_footer.png" />
                </a>
            </div>
            <div class="row-block">
                <strong class="Footer-title">{% translate "Навигация" %}</strong>
                <ul class="menu menu_vt Footer-menu">
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'home' %}">{% translate "Главная" %}</a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'products:products_list' %}">{% translate "Каталог" %}</a>
                    </li>
                    <li class="menu-item">
                        <a class="menu-link" href="{% url 'comparisons:comparison_list' %}">{% translate "Сравнение" %}</a>
                    </li>
                    {%  if request.user.is_authenticated %}
                        <li class="menu-item">
                            <a class="menu-link" href="{% url 'user:account' %}">{% translate "Профиль" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <div class="row-block">
                <strong class="Footer-title">{% translate "Контакты" %}</strong>
                <p>{% translate "Телефон" %}: 8.800.200.600<br>Email: xxx@meg.com<br></p>
                <ul class="menu menu_img menu_smallImg Footer-menuSoc">
                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialFooter/fb.svg' %}" alt="fb.svg" /></a>
                    </li>
                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialFooter/tw.svg' %}" alt="tw.svg" /></a>
                    </li>
                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialFooter/in.svg' %}" alt="in.svg" /></a>
                    </li>
                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialFooter/pt.svg' %}" alt="pt.svg" /></a>
                    </li>
                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialFooter/mail.svg' %}" alt="mail.svg" /></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

django_marketplace/templates/header.html
{%  load static %}
{% load mptt_tags %}
{% load carts_tags %}
{% load i18n %}

<header class="Header">
    <div class="ControlPanel">
        <div class="wrap">
            <div class="row ControlPanel-row">
                <div class="row-block">
                    <div class="row ControlPanel-rowSplit">
                        <div class="row-block hide_700">
                            <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                                <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialHeader/tw.svg' %}" alt="tw.svg" /></a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialHeader/in.svg' %}" alt="in.svg" /></a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialHeader/pt.svg' %}" alt="pt.svg" /></a>
                                </li>
                                <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'img/icons/socialHeader/mail.svg' %}" alt="mail.svg" /></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <nav class="row-block">
                    {% if not request.user.is_authenticated %}
                        <div class="row ControlPanel-rowSplit">
                            <div class="row-block">
                                <a class="ControlPanel-title" href ="{% url 'user:login' %}">{% translate 'Вход' %}</a>
                                <a class="ControlPanel-title" href ="{% url 'user:register' %}">{% translate 'Регистрация' %}</a>
                            </div>
                        </div>
                    {% endif %}
                </nav>
            </div>
        </div>
        <!--+div.menuModal#navigate
  //    +menu([
  //        ['Главная','index.html'],
  //        ['Портфолио','index.html'],
  //        ['Мои проекты','index.html'],
  //        ['Контакты','index.html']
  //    ], page === 'article'? 'Портфолио': 'Главная')._main

  block
  -->
    </div>
    <div class="wrap">
        <div class="row Header-rowMain">
            <div class="row-block Header-logo">
                <a class="logo" href="{% url 'home' %}">
                    <img class="logo-image" src="{% static 'img/logo.png' %}" alt="logo.png" />
                </a>
            </div>
            {% if not simple_header %}
                <nav class="row-block row-block_right Header-menu">
                    <div class="menuModal" id="navigate">
                        <ul class="menu menu_main">
                            <li class="menu-item">
                                <a class="menu-link" href="{% url 'home' %}">{% translate "Главная" %}</a>
                            </li>
                            <li class="menu-item">
                                <span class="menu-label menu-label_success">{% translate "Скидки" %}</span>
                                <a class="menu-link" href="{% url 'products:products_list' %}">{% translate "Каталог" %}</a>
                            </li>
                            <li class="menu-item">
                                <a class="menu-link" href="{% url 'comparisons:comparison_list' %}">{% translate "Сравнение" %}</a>
                                {% if comparison_count > 0 %}
                                <samp class="CartBlock-amount">{{ comparison_count }}</samp>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </nav>
                <div class="row-block">
                    <div class="CartBlock">
                        <div class="dropdown">
                            {%  if request.user.is_authenticated %}
                                <button class="dropbtn">
                                    <img class="CartBlock-img" src="{% static 'img/icons/loon-icon.svg' %}" alt="loon-icon.svg" />
                                </button>
                            {% endif %}
                            <div class="dropdown-content">
                                <a class="dropdown-content-a" href="{% url 'user:account' %}">{% translate "Личный кабинет" %}</a>
                                <a class="dropdown-content-a" href="/admin">{% translate "Административный раздел" %}</a>
                                <form id="logout-form" action="{% url 'user:logout' %}" method="post">
                                    <a class="dropdown-content-a" href="#" onclick="document.getElementById('logout-form').submit(); return false;">
                                        {% translate "Выход" %}
                                    </a>
                                    {% csrf_token %}
                                </form>
                            </div>
                        </div>
                        <a class="CartBlock-block" href="{% url 'carts:cart' %}">
                            <img class="CartBlock-img" src="{% static 'img/icons/cart.svg' %}" alt="cart.svg" />
                            <span class="CartBlock-amount">
                                {% quantity_products request %}
                            </span>
                    </a>
                    <div class="CartBlock-block">
                        {% total_price request carts as price %}
                        {% if price %}
                            <span class="CartBlock-price">
                                {{ price.total_price }}$
                            </span>
                        {% endif %}
                    </div>
                    {% get_current_language as CURRENT_LANGUAGE %}
                    {% get_available_languages as AVAILABLE_LANGUAGES %}
                    <div class="dropdown CartBlock-block">
                        <button class="dropbtn" style="display: flex;">
                            <img class="CartBlock-img" src="{% static 'img/icons/lan.svg' %}" alt="lan.svg"/>
                        </button>
                        <div class="dropdown-content">
                            {% for lang in AVAILABLE_LANGUAGES %}
                            <a class="dropdown-content-a" href="{% get_url request lang.0 %}" {% if lang.0 == CURRENT_LANGUAGE %} class="active" {% endif %}>
                                {{ lang.1 }}
                            </a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-block Header-trigger"><a class="menuTrigger" href="#navigate">
                <div class="menuTrigger-content">{% translate "Навигация" %}
                </div>
                <span></span><span></span><span></span>
            </a>
            </div>
            {% endif %}
        </div>
    </div>
    {% if not simple_header %}
    <div class="Header-searchWrap">
        <div class="wrap">
            <div class="Header-categories">
                <div class="CategoriesButton">
                    <div class="CategoriesButton-title">
                        <div class="CategoriesButton-icon">
                            <img src="{% static 'img/icons/allDep.svg' %}" alt="allDep.svg"/>
                        </div>
                        <span class="CategoriesButton-text">{% translate "Все категории" %}</span>
                        <div class="CategoriesButton-arrow">
                        </div>
                    </div>
                    <div class="CategoriesButton-content">
                        <ul class="CategoriesButton-link">
                            <a href="{% url 'products:discounts_list' %}">
                                <div class="CategoriesButton-icon">
                                    <img src="{% static 'img/icons/departments/4.svg' %}" alt="4.svg" />
                                </div>
                                <span class="CategoriesButton-text">{% translate "Скидки" %}</span>
                            </a>
                        </ul>
                        {% recursetree list_categories %}
                        <ul class="CategoriesButton-link">
                            <a href="{% url 'products:products_list' %}?category={{ node.id }}">
                                <div class="CategoriesButton-icon">
                                    <p>OO</p>
                                </div>
                                <span class="CategoriesButton-text">{{ node.name }}</span>
                            </a>
                            {% if not node.is_leaf_node %}
                            <a class="CategoriesButton-arrow" href="" {% url 'products:products_list' %}?category={{ node.id }}""></a>
                            {% endif %}
                            {% if not node.is_leaf_node %}
                            <ul class="CategoriesButton-submenu">
                                {{ children }}
                            </ul>
                            {% endif %}
                        </ul>
                        {% endrecursetree %}
                    </div>
                </div>
            </div>
            <div class="Header-searchLink"><img src="{% static 'img/icons/search.svg' %}" alt="search.svg"/>
            </div>
            <div class="Header-search">
                <div class="search">
                    <form class="form form_search" action="{% url 'products:products_list' %}" method="post">
                        {% csrf_token %}
                        <input class="search-input" id="query" name="name" type="text"
                               placeholder="NVIDIA GeForce RTX 3060"/>
                        <button class="search-button" type="submit" name="search" id="search">
                            <img src="{% static 'img/icons/search.svg' %}" alt="search.svg"/>{% translate "Поиск" %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</header>